DROP TABLE IF EXISTS user_meta;
DROP TABLE IF EXISTS customize;
DROP TABLE IF EXISTS media;
DROP TABLE IF EXISTS tenants;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS user_groups;
DROP TABLE IF EXISTS users;
