CREATE TABLE users (
  id TEXT PRIMARY KEY NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE user_groups (
  id TEXT PRIMARY KEY NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  name TEXT NOT NULL,
  owner_id TEXT NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE user_roles (
  id TEXT PRIMARY KEY NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  name TEXT NOT NULL,
  owner_id TEXT NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE tenants (
  id TEXT PRIMARY KEY NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  owner_id TEXT NOT NULL,
  FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE media (
  id TEXT PRIMARY KEY NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  owner_id TEXT NOT NULL,
  name TEXT,
  type TEXT,
  size INTEGER,
  data BLOB,
  FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE customize (
  id TEXT PRIMARY KEY NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  data TEXT,
  tenant_id TEXT NOT NULL,
  FOREIGN KEY (tenant_id) REFERENCES tenants (id)
);

CREATE TABLE user_meta (
  id TEXT PRIMARY KEY NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  owner_id TEXT NOT NULL,
  user_groups TEXT NOT NULL,
  user_roles TEXT NOT NULL,
  uniq_customize TEXT,
  FOREIGN KEY (owner_id) REFERENCES users (id),
  FOREIGN KEY (user_groups) REFERENCES user_groups (id),
  FOREIGN KEY (user_roles) REFERENCES user_roles (id)
);
